server:
  port: 8999
  servlet:
    context-path: /api


spring:
  # 激活配置文件
  profiles:
    # TODO 配置自己的配置文件
    active: local

  # 数据库配置
  datasource:
    # TODO 配置自己的数据库
    url: jdbc:mysql://localhost:3306/boot3_initial_db
    username: root
    password: 123

  # Redis 配置
  data:
    redis:
      # TODO 配置自己的 Redis 环境
      host: localhost
      username: default
      password: 123456
      port: 6379
      database: 0
  session:
    # session 3 天过期
    timeout: 259200

# 自定义配置
custom:
  # 自定义日期格式配置
  dateformat:
    date: yyyy-MM-dd
    datetime: yyyy-MM-dd HH:mm:ss
    time: HH:mm:ss

  # OSS 配置
  oss:
    aliyun:
      endpoint: ${oss.aliyun.endpoint}
      region: ${oss.aliyun.region}

# knife4j 文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'

      # TODO 注意更改包名
      packages-to-scan: com.wolfhouse.springboot3initial.mvc.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn